PROFILE_ID="youtube_app_strong"
PROFILE_NAME="YouTube App Strong"

ENGINE="nfqws2"
ENABLED="true"

TCP_PORTS="443"
UDP_PORTS="443"

MODE="global"

PRESET_FILE=""
TCP_STRATEGY="hostfakesplit_multi_google_tcp_ts"
UDP_STRATEGY="fake_6_google_quic"
STUN_STRATEGY=""

TCP_HOSTLIST="/data/adb/modules/zapret2_manager/files/config/hostlists/youtube.txt"
TCP_IPSET=""
UDP_HOSTLIST=""
UDP_IPSET="/data/adb/modules/zapret2_manager/files/config/ipsets/youtube.txt"

NFQWS2_BIN="nfqws2"
NFQWS2_DEBUG="1"
NFQWS2_QNUM="200"
NFQWS2_INTERCEPT="1"
NFQWS2_DRY_RUN="false"

NFQWS2_FILTER_TCP=""
NFQWS2_FILTER_UDP=""
NFQWS2_ARGS=""
ARGS=""