SERVICE_ID="chatgpt"
SERVICE_NAME="ChatGPT"
ENABLED="true"
DEFAULT_TCP_HOSTLIST="$CFG_DIR/hostlists/chatgpt.txt"
DEFAULT_TCP_IPSET="$CFG_DIR/ipsets/chatgpt.txt"
DEFAULT_UDP_HOSTLIST=""
DEFAULT_UDP_IPSET="$CFG_DIR/ipsets/chatgpt.txt"
DEFAULT_STUN_HOSTLIST=""
DEFAULT_STUN_IPSET=""
DEFAULT_TCP_STRATEGY=""
DEFAULT_UDP_STRATEGY=""
DEFAULT_STUN_STRATEGY=""
