SERVICE_ID="instagram"
SERVICE_NAME="Instagram"
ENABLED="true"
DEFAULT_TCP_HOSTLIST="$CFG_DIR/hostlists/instagram.txt"
DEFAULT_TCP_IPSET=""
DEFAULT_UDP_HOSTLIST=""
DEFAULT_UDP_IPSET="$CFG_DIR/ipsets/instagram.txt"
DEFAULT_STUN_HOSTLIST=""
DEFAULT_STUN_IPSET=""
DEFAULT_TCP_STRATEGY="hostfakesplit_multi_google_tcp_ts"
DEFAULT_UDP_STRATEGY="fake_6_google_quic"
DEFAULT_STUN_STRATEGY=""
