SERVICE_ID="telegram"
SERVICE_NAME="Telegram"
ENABLED="true"
DEFAULT_TCP_HOSTLIST="$CFG_DIR/hostlists/telegram.txt"
DEFAULT_TCP_IPSET="$CFG_DIR/ipsets/telegram.txt"
DEFAULT_UDP_HOSTLIST=""
DEFAULT_UDP_IPSET=""
DEFAULT_STUN_HOSTLIST=""
DEFAULT_STUN_IPSET=""
DEFAULT_TCP_STRATEGY="syndata_multisplit_tls_google_700"
DEFAULT_UDP_STRATEGY=""
DEFAULT_STUN_STRATEGY=""
