SERVICE_ID="x"
SERVICE_NAME="X"
ENABLED="true"
DEFAULT_TCP_HOSTLIST="$CFG_DIR/hostlists/x.txt"
DEFAULT_TCP_IPSET=""
DEFAULT_UDP_HOSTLIST=""
DEFAULT_UDP_IPSET="$CFG_DIR/ipsets/x.txt"
DEFAULT_STUN_HOSTLIST=""
DEFAULT_STUN_IPSET=""
DEFAULT_TCP_STRATEGY="syndata_multisplit_tls_google_700"
DEFAULT_UDP_STRATEGY="fake_6_google_quic"
DEFAULT_STUN_STRATEGY=""
