SERVICE_ID="instagram"
ENABLED="true"
MODE="direct"
VPN_PROFILE="active"
TCP_STRATEGY="hostfakesplit_multi_google_tcp_ts"
UDP_STRATEGY="fake_6_google_quic"
STUN_STRATEGY=""
TCP_HOSTLIST="$CFG_DIR/hostlists/instagram.txt"
TCP_IPSET="$CFG_DIR/ipsets/instagram.txt"
UDP_HOSTLIST=""
UDP_IPSET="$CFG_DIR/ipsets/instagram.txt"
STUN_HOSTLIST=""
STUN_IPSET=""
