SERVICE_ID="telegram"
ENABLED="true"
MODE="direct"
VPN_PROFILE="active"
TCP_STRATEGY="syndata_multisplit_tls_google_700"
UDP_STRATEGY=""
STUN_STRATEGY=""
TCP_HOSTLIST="$CFG_DIR/hostlists/telegram.txt"
TCP_IPSET="$CFG_DIR/ipsets/telegram.txt"
UDP_HOSTLIST=""
UDP_IPSET=""
STUN_HOSTLIST=""
STUN_IPSET=""
