SERVICE_ID="youtube"
ENABLED="true"
MODE="zapret"
VPN_PROFILE="active"
TCP_STRATEGY="syndata_multidisorder_tls_google_700"
UDP_STRATEGY="fake_6_google_quic"
STUN_STRATEGY=""
TCP_HOSTLIST="$CFG_DIR/hostlists/youtube.txt"
TCP_IPSET="$CFG_DIR/ipsets/youtube.txt"
UDP_HOSTLIST=""
UDP_IPSET="$CFG_DIR/ipsets/youtube.txt"
STUN_HOSTLIST=""
STUN_IPSET=""
